In [1]:
import numpy as np 

In [7]:
A = np.array([[-1,2,1],[4,0,2],[3,2,-5]], dtype = float)

a = A[0][0]
b = A[0][1]
c = A[0][2]
x = A[1][0] / a
d = A[1][1] - (x * b)
e = A[1][2] - (x * c)
y = A[2][0] / a
z = (A[2][1] - (y * b)) / d
f = A[2][2] - (y * c + z * e)

print (f) # u33
L = np.array([[1,0,0],[x,1,0],[y,z,1]], dtype = float)
U = np.array([[a,b,c],[0,d,e],[0,0,f]], dtype = float)
print ("L: \n", L)
print ("U: \n",U)
print (L @ U)


-8.0
L: 
 [[ 1.  0.  0.]
 [-4.  1.  0.]
 [-3.  1.  1.]]
U: 
 [[-1.  2.  1.]
 [ 0.  8.  6.]
 [ 0.  0. -8.]]
[[-1.  2.  1.]
 [ 4.  0.  2.]
 [ 3.  2. -5.]]
